### ISSUE TITLE
Violation of HOCON license agreement

### ISSUE THREAD

**Issue by Aaronontheweb** [lizoc/jsonplus#4]
Hi there,

So it appears that this is an identical issue to https://github.com/lizoc/textscript/issues/3

https://twitter.com/torn_hoof/status/1078642973544456192

You've cloned a copy of the [Akka.NET project's HOCON library](https://github.com/akkadotnet/HOCON), renamed all of the classes and namespaces, removed our copyright headers, and changed the license used on the repository. All without changing the substance of what the library does.

You're free to fork our library and use it under the terms of the Apache 2.0 license, provided that all notices and copyright headers are kept intact - which you have not done. Even if you want to rename it, rebrand it, and release a new NuGet package etc - that's all fine, but you still need to keep our original license agreement if you want to use our source code. ReSharper-ing the names of classes and files doesn't release you from this requirement.

To resolve this issue, we demand that all copyright headers and the original license terms be restored. 

I should also point out that Akka.NET is a .NET Foundation Project and they are the license holder to the HOCON library.

**Comment by imacks** [comment]
Erm...yeah I get your point. But just to be clear, your project did not have copyright header on every source code file when I was forking, and therefore nothing was intentionally removed.

I did took the liberty of including your license in the THIRD-PARTY-LICENSE document. If you want, I can always add a big banner at the top that says we're forked from `HOCON.NET`. Is that the gist of your request?

**Comment by imacks** [comment]
Actually, I'm getting tired of this violation trending stuff going on. I studied your code some months ago and tried to build on it. Features, bugfix and changes made, all hopefully for the better. In fact, I contributed back to your repo with solutions to problems I found. Fast forward to now, you suddenly decided to put copyright headers on every source file, and start demanding that I do the same. That's just awful. I'm sorry I didn't use the github fork feature on this repo, but pls don't make it look like I'm stealing from you.

So going forward, I'm going to put a big banner at the top of the readme that says this is a hard fork from xxx. Hope that works for you.

**Comment by Aaronontheweb** [comment]
No, it is not good enough. You added _your own copyright header_ to the code, which you do not own and is not subject to your the `LICENSE.MD` in your repository, as it currently stands.

**Comment by imacks** [comment]
It says mine and others (see THIRD-PARTY-LICENSE). But if you insist I can remove my own copyright headers, which restores it to the original state.

So are you saying that I should replace my LICENSE.md with yours instead?

**Comment by imacks** [comment]
Sorry I didn't hear back from you, so I went ahead to update the README for the purpose of clarifying the fork. Feel free to open a separate issue if you are still having problems.
